services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  DW\Trainingsplatz\:
    resource: '../Classes/*'
    exclude: 
      - '../Classes/Domain/Model/Answer'
      - '../Classes/Domain/Model/Infomail'
      - '../Classes/Domain/Model/Intensity'
      - '../Classes/Domain/Model/Map'
      - '../Classes/Domain/Model/Motivation'
      - '../Classes/Domain/Model/Sport'
      - '../Classes/Domain/Model/Template'
      - '../Classes/Domain/Model/Training'

  DW\Trainingsplatz\Domain\Repository\UserRepository:
    public: true

  DW\Trainingsplatz\Command\InfomailCommand:
    tags:
      - name: 'console.command'
        command: 'trainingsplatz:infomail'
        description: 'Send Training InfoMails'
        hidden: false

  DW\Trainingsplatz\Property\TypeConverter\BitConverter:
    tags:
      - name: extbase.type_converter
        priority: 100
        target: int
        sources: array,int
  
  In2code\Femanager\Controller\EditController: '@DW\Trainingsplatz\Controller\EditController'
  In2code\Femanager\Controller\NewController: '@DW\Trainingsplatz\Controller\NewController'
  In2code\Femanager\Domain\Model\User: '@DW\Trainingsplatz\Domain\Model\User'
  In2code\Femanager\Domain\Repository\UserRepository: '@DW\Trainingsplatz\Domain\Repository\UserRepository'
